spring:
  datasource:
    url: jdbc:postgresql://localhost:5431/dbPracticum
    username: admin
    password: dbPracticum
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: demo
  security:
    key: 8074658237c236e39e96e909ac1abb25a3e1773b100096ad6877c439cd452c17

server:
  port:
    8000

logging:
  level:
    ru.tbank.practicum.service: DEBUG
    ru.tbank.practicum: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - [%mdc] %msg%n"