spring:
  datasource:
    url: jdbc:postgresql://localhost:5431/dbPracticum
    username: admin
    password: dbPracticum
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
    drop-first: false
    default-schema: public

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: demo

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: group1
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: emailEvent:org.example.dto.events.EmailEvent

  security:
    key:

  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: "*"
          connectiontimeout: 10000
          timeout: 10000
          writetimeout: 10000
    default-encoding: UTF-8

server:
  port: 8080

logging:
  level:
    org.example.service: DEBUG
    org.example: INFO
    liquibase: DEBUG
    org.springframework.mail: DEBUG
    com.sun.mail: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - [%mdc] %msg%n"